name: Lint and build check

on: [push]

jobs:
    main:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Install NPM dependencies
              run: npm ci

            - name: Lint check
              run: npm run lint

            - name: build check
              run: npm run build

            - name: Install Pint
              run: composer require laravel/pint

            - name: Run Pint check
              run: ./vendor/bin/pint --test
